wegrenproject/wegrenproject/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from wegrenapp import views

app_name = 'wegrenapp'
router = routers.DefaultRouter()

router.register('branches', views.HrmBranchAPI)
router.register('organizations', views.HrmOrganizationAPI)
#router.register('formdropdowns', views.HrmFormDropdownAPI)
router.register('formfield', views.HrmFormFieldAPI)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    #path('api/org/',views.org,name='org'),
    
    path('api/formmaster/',views.formmaster,name='formmaster'),
    path('api/formmaster/show/',views.show,name='showformmaster'),
    path('api/formmaster/edit/<int:id>',views.edit,name='editformmaster'),
    path('api/formmaster/update/<int:id>',views.update,name='updateformmaster'),
    path('api/formmaster/delete/<int:id>',views.destroy,name='destroyformmaster'),
    path('ajax/load-branches/', views.load_branches, name='ajax_load_branches')
]

wegrenproject/wegrenapp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class HrmBranch(models.Model):
    branchname = models.CharField(max_length=255)
    orgid = models.ForeignKey('HrmOrganization', models.DO_NOTHING, db_column='orgid')

    class Meta:
        managed = False
        db_table = 'hrm_branch'


class HrmDynamicFormDropdown(models.Model):
    dropdown_label = models.CharField(max_length=255)
    dropdown_value = models.CharField(max_length=255)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    form_field = models.ForeignKey('HrmDynamicFormField', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'hrm_dynamic_form_dropdown'


class HrmDynamicFormField(models.Model):
    field_title = models.CharField(max_length=255)
    field_description = models.CharField(max_length=500)
    field_type = models.IntegerField()
    field_original_name = models.CharField(max_length=50, blank=True, null=True)
    field_hidden = models.SmallIntegerField()
    field_order = models.IntegerField()
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    form_master = models.ForeignKey('HrmDynamicFormMaster', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'hrm_dynamic_form_field'


class HrmDynamicFormMaster(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=1000, blank=True, null=True)
    form_url = models.CharField(max_length=500)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    branch = models.ForeignKey(HrmBranch, models.DO_NOTHING, blank=True, null=True)
    organization = models.ForeignKey('HrmOrganization', models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'hrm_dynamic_form_master'


class HrmOrganization(models.Model):
    orgname = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'hrm_organization'

wegrenproject/wegrenapp/forms.py
from django import forms  
from wegrenapp.models import *  
class HrmOrganizationForm(forms.ModelForm):  
    class Meta:  
        model = HrmOrganization  
        fields = "__all__" 

class HrmDynamicFormMasterForm(forms.ModelForm):
	class Meta:
		model=HrmDynamicFormMaster
		fields="__all__"

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['branch'].queryset = HrmBranch.objects.none()
		if 'organization' in self.data:
		    try:
		        orgid = int(self.data.get('organization'))
		        self.fields['branch'].queryset = HrmBranch.objects.filter(orgid=orgid).order_by('branchname')
		    except (ValueError, TypeError):
		        pass  # invalid input from the client; ignore and fallback to empty organization queryset
		elif self.instance.id:
			self.fields['branch'].queryset = self.instance.organization.branches.order_by('branchname')

wegrenproject/wegrenapp/views.py
from django.shortcuts import render, redirect
from rest_framework import viewsets
from wegrenapp.forms import *
from wegrenapp.models import *
from .serializers import *

class HrmBranchAPI(viewsets.ModelViewSet):
    serializer_class = HrmBranchSerializer
    queryset = HrmBranch.objects.all()

class HrmOrganizationAPI(viewsets.ModelViewSet):
    serializer_class = HrmOrganizationSerializer
    queryset = HrmOrganization.objects.all()

class HrmFormDropdownAPI(viewsets.ModelViewSet):
    serializer_class = HrmFormDropdownSerializer
    queryset = HrmDynamicFormDropdown.objects.all()

class HrmFormFieldAPI(viewsets.ModelViewSet):
    serializer_class = HrmFormFieldSerializer
    queryset = HrmDynamicFormField.objects.all()

    """def create(self, request, *args, **kwargs):
        response = super(HrmFormFieldAPI, self).create(request, *args, **kwargs)
        # here may be placed additional operations for
        # extracting id of the object and using reverse()
        
        
        if request.POST.get("field_type","")=='2':
                                    
            return redirect('/api/formdropdowns/')
        return response"""

    
class HrmFormMasterAPI(viewsets.ModelViewSet):
    serializer_class = HrmFormMasterSerializer
    queryset = HrmDynamicFormMaster.objects.all()


def formmaster(request):  

    if request.method == "POST":  
        form = HrmDynamicFormMasterForm(request.POST)
        print("Form has been posted")
        print(form)
        if form.is_valid():
            print("Form is valid")    
            try:

                form.save()  
                
                return redirect('/api/formmaster/show/')  
            except:  
                pass  
    else:  
        form = HrmDynamicFormMasterForm()
        print("Form data needs to be checked")
        print(form)
    orgs=HrmOrganization.objects.all()
    return render(request,'index.html',{'form':form,'organizations':orgs})
def show(request):  
    formmasters = HrmDynamicFormMaster.objects.all()
    return render(request,"show.html",{'formmasters':formmasters})  
def edit(request, id):  
    formmasters = HrmDynamicFormMaster.objects.get(id=id)  
    return render(request,'edit.html', {'formmaster':formmaster})  
def update(request, id):  
    formmasters = HrmDynamicFormMaster.objects.get(id=id)  
    form = HrmDynamicFormMaster(request.POST, instance = formmaster)  
    if form.is_valid():  
        form.save()  
        return redirect("/api/formmaster/show/")  
    return render(request, 'edit.html', {'formmaster': formmaster})  
def destroy(request, id):  
    formmaster = HrmDynamicFormMaster.objects.get(id=id)  
    formmaster.delete()  
    return redirect("/api/formmaster/show/")  

def load_branches(request):
    org_id = request.GET.get('organization')
    branches = HrmBranch.objects.filter(orgid=org_id).order_by('branchname')
    return render(request, 'branch_dropdown_list_options.html', {'branches': branches})

wegrenproject/wegrenapp/templates/branch_dropdown_list_options.html
<option value="">---------</option>
{% for branch in branches %}
<option value="{{ branch.id }}">{{ branch.branchname }}</option>
{% endfor %}

wegrenproject/wegrenapp/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/api/formmaster/update/{{formmaster.id}}/">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormmaster Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="id" id="id_formmasterid" required maxlength="20" value="{{ formmaster.id }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormMaster Title:</label>  
    <div class="col-sm-4">  
        <input type="text" name="title" id="id_title" required maxlength="255" value="{{ formmaster.title }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormMaster Description:</label>  
    <div class="col-sm-4">  
        <input type="text" name="description" id="id_description" required maxlength="1000" value="{{ formmaster.description }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormMaster FormURL:</label>  
    <div class="col-sm-4">  
        <input type="text" name="formurl" id="id_formurl" required maxlength="100" value="{{ formmaster.formurl }}" />  
    </div>  
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormMaster Created At:</label>  
    <div class="col-sm-4">  
        <input type="datetime-local" name="formurl" id="id_formurl" required value="{{ formmaster.createdat }}" />  
    </div>  
  </div> <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormMaster Updated At:</label>  
    <div class="col-sm-4">  
        <input type="datetime-local" name="formurl" id="id_formurl" required value="{{ formmaster.updatedat }}" />  
    </div>  
  </div> <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormMaster Organization ID:</label>  
    <div class="col-sm-4">  
        <input type="text" name="formurl" id="id_formurl" required maxlength="100" value="{{ formmaster.orgid }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormMaster Branch:</label>  
    <div class="col-sm-4">  
        <select name="item_branchid">
{% for branch in branches %}
    <option value="{{ branch.id }}">{{ branch.branchname }}</option>
{% endfor %}
</select>
        <!--<input type="text" name="formurl" id="id_formurl" required maxlength="100" value="{{ formmaster.branchid }}" />  -->
    </div>  
  </div> 

    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>

wegrenproject/wegrenapp/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    
</head>  
<body>  
<form method="POST" id="masterform" class="post-form" data-branches-url="{% url 'ajax_load_branches' %}" action="/api/formmaster">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">HrmDynamicFormMaster Id:</label>  
    <div class="col-sm-4">  
      {{ form.id }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">HrmDynamicFormMaster Title:</label>  
    <div class="col-sm-4">  
      {{ form.title }}  
    </div>  
  </div>  
    
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormMaster Description:</label>  
    <div class="col-sm-4">  
        {{ form.description }}
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormMaster FormURL:</label>  
    <div class="col-sm-4">  
        {{ form.form_url }}"
    </div>  
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormMaster Created At:</label>  
    <div class="col-sm-4">  
        <!--{{ form.created_at }}-->
        <input type="datetime-local" name="created_at" required id="id_created_at">

    </div>  
  </div> <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormMaster Updated At:</label>  
    <div class="col-sm-4">  
        <!--{{ form.updated_at }}"-->
        <input type="datetime-local" name="updated_at" required id="id_updated_at">
    </div>  
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormMaster Organization:</label>  
    <div class="col-sm-4">  
        <select name="organizations" id="organizations">
          <option value="">------</option>
{% for org in organizations %}
    <option value="{{ org.id }}">{{ org.orgname }}</option>
{% endfor %}
</select>
        <!--<input type="text" name="formurl" id="id_formurl" required maxlength="100" value="{{ formmaster.branchid }}" />  -->
    </div>  
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DynamicFormMaster Branch :</label>  
    <div class="col-sm-4">  
        <select name ="branches" id="branches">
        </select>
    </div>  
  </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
   
</form>  

<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
    <!--<script type="text/javascript" src="http://yourjavascript.com/7174319415/script.js"></script>-->
        <script>
            $(document).ready(function(){
                 $('select#organizations').change(function () {
                     var optionSelected = $(this).find("option:selected");
                     var valueSelected  = optionSelected.val();
                     var org_name   = optionSelected.text();
                     var url =$("#masterform").attr('data-branches-url')
                     console.log("Organization selected is")
                     console.log(org_name)
                     data = {'orgname' : org_name ,'organization':valueSelected};
                     $.ajax({
                      url:url,
                      data:data,
                      success:function(data)
                      {
                       //$("#branch").html(data)
                       console.log("Branches are")
                       console.log(data);
                            //$("#branches option").remove();
                            //for (var i = data.length - 1; i >= 0; i--) {
                            //    $("#branches").append('<option val="'+data[i].id+'">'+ data[i].branchname +'</option>');
                            //};
                             $("#branches").html(data);
                        
                      }
                     });
                     
                 });
            });
        </script>
</body>  
</html>  

wegrenproject/wegrenapp/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Organization Records</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>FormMaster ID</th>  
        <th>FormMaster Name</th>  
        <!--<th>Employee Email</th>  
        <th>Employee Contact</th>  -->
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for formmaster in formmasters %}  
    <tr>  
        <td>{{ formmaster.id }}</td>  
        <td>{{ formmaster.title }}</td>  
        <td>  
            <a href="/api/formmaster/edit/{{ formmaster.id }}/"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/api/formmaster/delete/{{ formmaster.id }}/">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/api/formmaster/" class="btn btn-primary">Add New FormMaster</a></center>  
<center><a href="/api/formdropdowns/" class="btn btn-primary">Add New FormDropdown</a></center>  
<center><a href="/api/formfield/" class="btn btn-primary">Add New FormField</a></center>  
<center><a href="/api/formfield/" class="btn btn-primary">Add New Organization</a></center>  
<center><a href="/api/formfield/" class="btn btn-primary">Add New Branch</a></center>  
</body>  
</html>  